config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/about'
  get 'static_pages/help'
  get 'static_pages/contact'
  
  get '/signup',   to: "users#new"
  get    'login',  to: 'sessions#new'
  post   'login',  to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t('app_name') %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t('ftr_about'), static_pages_about_url %></li>
      <li><%= link_to t('ftr_contact'), static_pages_contact_url %></li>
      <li><%= link_to t('ftr_help'), static_pages_help_url %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#"><%= t('app_name').upcase %></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">

              <% if yield(:title) == 'Home' && logged_in? %>
                <li class="nav-item"><%= link_to t('hdr_home'), static_pages_home_url, class: "nav-link active" %></li>
              <% else %>
                <li class="nav-item"><%= link_to t('hdr_home'), static_pages_home_url, class: "nav-link" %></li>
              <% end %>
             
              <% if yield(:title) == 'Help' %>
                <li class="nav-item"><%= link_to t('hdr_help'), static_pages_help_url, class: "nav-link active" %></li>
              <% else %>
                  <li class="nav-item"><%= link_to t('hdr_help'), static_pages_help_url, class: "nav-link" %></li>
              <% end %>
            
            <% if logged_in? %>
                <% if yield(:title) == 'Users' %>
                  <li class="nav-item"><%= link_to "Users", users_path, class: "nav-link active" %></li>
                <% else %>
                  <li class="nav-item"><%= link_to "Users", users_path, class: "nav-link" %></li>
                <% end %>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <%= current_user.name %>
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><%= link_to "Profile", current_user, class: "dropdown-item" %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user), class: "dropdown-item" %></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><%= link_to t('hdr_logout'), logout_path, method: "delete", class: "dropdown-item" %></li>
                </ul>
              </li>
            <% else %>
              <li class="nav-item"><%= link_to t('hdr_login'), login_path, class: "nav-link active" %></li>
            <% end %>
          </ul>
          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('app_name') %> - <%= yield(:title) %></title>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= render 'layouts/shim' %>
    <!-- %= javascript_importmap_tags % -->
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>

</html>